[build]  
  publish = "static"  
  command = "mkdir -p static && cp -r templates static/ && cp -r static/* static/"  
  functions = "netlify/functions"  
    
[functions]  
  directory = "netlify/functions"  
  node_bundler = "esbuild"  

[[redirects]]  
  from = "/*"  
  to = "/.netlify/functions/api/:splat"  
  status = 200  
